### ISSUE TITLE
What does "Local Decrypt" option do?

### ISSUE THREAD

**Issue by florihupf** [haiwen/seafile-iOS#107]
I toggle it but I don't see any difference in behavior.

Esp. the photo browser and the image thumbnails still don't work.  I would expect them to work.

**Comment by poetwang** [comment]
The "Local Decrypt" options means that the file will be decrypted on client side and the password will never be sent to the server. This option is only for security.  When it is enabled, the server wont have the password to decrypt the image, so is unable to generate the thumbnails.

We won't  generate the thumbnails on the server for encrypted library because we do not want to cache the thumbnails on the server, this may lead to security issues.

**Comment by florihupf** [comment]
I understand the server part, thank you!

Does it also mean that the iOS client should be able to display photo
browser and thumbnails if it can decode locally?

Because both things are not working...

:)

~ Florian

**Comment by poetwang** [comment]
The client can only generate the thumbnails after download the origin image and decode locally.
