### ISSUE TITLE
open file from other application does not work

### ISSUE THREAD

**Issue by moetiker** [haiwen/seafile-iOS#138]
Hi

on my iphone ios 10.1.1 I'm using a scanner application to scan files and upload them with the
open with command to seafile app. 

till probably the last update seafile app was opening and asking where to store the file
now seafile is opening but it looks like seafile does not receive any file from the scanner app.

was there a change? if I selecting an other application to receive the file like google drive it works.

cheers Manuel

**Comment by poetwang** [comment]
It is a bug, will be fixed in the next version.

**Comment by GITchristoph** [comment]
Hi poet

I still can't access the seafile from Word.app on iOS devices (iPhone 7 and iPadPro 9.7).
Seafile Server 6.0.6.

Was it supposed to be fixed in the recently released update?

Greetings, Chris

**Comment by poetwang** [comment]
@GITchristoph could you share more details about how to reproduce this bug?

**Comment by GITchristoph** [comment]
My bug is this:

I open word.app on an iOS device (testet on iPad and iPhone)
Chose "Open - ...more - Locations - Seafile"
And then the dialog window disappears instead of allowing the user to chose a location/file in seafile. 

Can you reproduce that?

Kind Regards

Christoph Kuhnert




On 7 Dec 2016, at 19:24, poet <notifications@github.com> wrote:

@GITchristoph could you share more details about how to reproduce this bug?

**Comment by poetwang** [comment]
@GITchristoph  Thanks, I can reproduce that, will fix it soon.

**Comment by GITchristoph** [comment]
Thanks, sounds great ;-)

Kind Regards

Chris




On 8 Dec 2016, at 23:15, poet <notifications@github.com> wrote:

@GITchristoph Thanks, I can reproduce that, will fix it soon.

**Comment by GITchristoph** [comment]
This works now for me. 

Thanks a lot,  Chris
