### ISSUE TITLE
Problem setting up account with HTTPS

### ISSUE THREAD

**Issue by muellefr** [haiwen/seafile-iOS#175]
Using Seafile Pro Client Version 2.6.3, setting up an account via HTTPS only works while manually typing "https://" although the gui suggests there would be no need to specify this a second time. Ending up with "https://https://".

After logging out from account logging back in is impossible because https:// gets stripped from the url.

**Comment by egroeper** [comment]
Pehaps this wasn't clear enough. Currently Login / account creation is not working anymore (for users)!
Please fix this!

This is **not** working:
![seafile-ios_login-not_working](https://user-images.githubusercontent.com/535113/29970049-5537cf12-8f23-11e7-9d3f-95c4607ca846.PNG)

This works on **first** login **only**:
![seafile-ios_login-working](https://user-images.githubusercontent.com/535113/29970048-5536939a-8f23-11e7-94ad-3a6a862c8742.PNG)

It would be great, if you would combine fixing this with implementing #167.

Currently, if the auth-token gets invalidated, the user has to remove his account and recreate it again to access his data on his iOS device. That's because after the first login the additional "https://" gets stripped and on (re-)login you can't modify the server field.

**Comment by egroeper** [comment]
Seems like we forgot to mention: This is about Shibboleth login.

**Comment by freeplant** [comment]
Does the problem only happen with Shibboleth login?

**Comment by egroeper** [comment]
Yes. I can't reproduce this with a local account.

**Comment by shoeper** [comment]
Just to have it on record: here is a user having the same issue.

https://forum.seafile.com/t/problem-with-shibboleth-login-on-mobile-clients/3807

**Comment by muellefr** [comment]
Looks like this has been fixed. I just checked iOS client 2.6.8 and the https-switch is turned on by default for shiboleth and it is greyed out so the user will be unable to setup an account without encryption.
