### ISSUE TITLE
Uploaded photos discarding editorial changes.

### ISSUE THREAD

**Issue by nightowl82** [haiwen/seafile-iOS#405]
I noticed since the last update that when I sync or upload (at least a jpeg or png) image, it uploads the "original" and discard my changes to the photo. (Changes like cropping, text, roation, etc…)

if this is intentional, some kind of option or setting should be given for photo uploading.

**Comment by henry9610** [comment]
Thank you for bringing this to our attention! In this version, we made optimizations to the upload process, which inadvertently affected the way edited images were handled. We have since reverted to the previous logic to ensure that your changes, such as cropping, text, or rotation, are preserved during uploads, and this fix will be included in the upcoming version, which will be released shortly.
