### ISSUE TITLE
image auto sync does not detect new photos

### ISSUE THREAD

**Issue by scarface-** [haiwen/seafile-iOS#50]
On my iphone5 (iOS 8.1.2) image auto sync in seafile 1.9.3 does not detect automatically when new photos are taken. I have to refresh the library screen in the app manually to start the upload of new photos.

**Comment by poetwang** [comment]
Did it still happen in 1.9.4?

**Comment by scarface-** [comment]
yes, still the same with 1.9.4

**Comment by bst27** [comment]
Same problem here. It sometimes works in a non predictable manner. Some uploaded photos are also broken.

My device is an iPhone 5S with iOS 8.1.2 (12B440) installed and Seafile version 1.9.4 with seacloud.cc account.

**Comment by poetwang** [comment]
The image will be auto synced in the background, and will not be shown on the screen. But when it is uploaded, you can see it by refreshing the "Camera Uploads" directory.

**Comment by bst27** [comment]
I would prefer to see the syncing progress, especially while syncing for the first time which can take a long time. At the moment I am just able to guess whether it completed syncing by watching at the activity stream and the time of the last change: If there is no new file for the last x minutes it probably finished.

**Comment by GITchristoph** [comment]
The upload function seems to work (somehow), but it's a bit hard to understand:
- what actually needs to be done to initiate the upload
  - simply start Seafile?
  - start Seafile and access the photo folder?
  - refresh the folder?
- when the upload started / is running / ended
- if the upload progresses if the user sends the seafile app after to the background?

Maybe a *two - three line comment* in the settings would already help the situation by informing the users what to do and to expect. 
Proposal:
![img_4513](https://cloud.githubusercontent.com/assets/4885236/6125703/51ce7b22-b119-11e4-9ccd-35ba4514f831.PNG)

Obviously the correct procedure needs to be explained there. I made mine up because of my questions above ;-)

What do you think?

**Comment by poetwang** [comment]
Sounds  good, maybe show the uploading status and the number of photos remaining is a good idea.

**Comment by bst27** [comment]
The new version shows a small progress bar for manually added files. This is a good feature I think.

![](http://i.imgur.com/ggGhh9z.jpg)

**Comment by bst27** [comment]
Where or how can I view the auto upload status listed in the update notes?

**Comment by lobermann** [comment]
Have the same issues here with iPhone 6 (iOS 8.1.3) and Version 1.9.6. It doesnt detect new pictures, and also does not allow me to disable the camera upload. As soon as you go back into the settings it is enabled again. When checking the library it says "Waiting for Upload" on most of the pictures, but nothing happens. Thats the only way I can get it to upload the pictures, by keeping the library screen open, otherwise no upload is happening.

**Comment by thewilli** [comment]
@lobermann I have the same problem: Once you enable photo sync, it can't be disabled. @poetwang Should we create a separate issue for the '*cannot disable photo sync*' problem?

**Comment by poetwang** [comment]
fixed in 1.9.8
