### ISSUE TITLE
EXIF data: on upload of picture, shot date is overwritten with upload date

### ISSUE THREAD

**Issue by postmod** [haiwen/seafile-iOS#95]
on upload on server via seafile ios app (manual selection from photo library in ios) the shot date is overwritten with the upload date (or copy to seafile app date?). 

The upload date is also shown in the ios app and is used for the "sort by date last changed" function

Example: Photo was taken on oct 7th and uploaded on the 15th. Mdls tool on the mac shows

kMDItemContentCreationDate     = 2015-10-15 20:18:45 +0000
kMDItemContentModificationDate = 2015-10-15 20:18:45 +0000
kMDItemFSContentChangeDate     = 2015-10-15 20:18:45 +0000
kMDItemFSCreationDate          = 2015-10-15 20:18:45 +0000

Seafile ios App v 2.1.2 on ios 9.1
Thank you!

**Comment by poetwang** [comment]
I use the exiftool to get the photo metadata. The Date/Time Original, Create Date remains the shot date. The time "File Modification Date/Time" is the timestamp in filesystem. It will update according to the rules of filesystem.
ExifTool Version Number         : 10.00
File Name                       : IMG_0055.JPG
Directory                       : .
File Size                       : 1495 kB
File Modification Date/Time     : 2015:11:07 15:41:50+08:00
File Access Date/Time           : 2015:11:07 15:42:27+08:00
File Inode Change Date/Time     : 2015:11:07 15:41:50+08:00
File Permissions                : rw-r-----
File Type                       : JPEG
File Type Extension             : jpg
MIME Type                       : image/jpeg
JFIF Version                    : 1.01
Exif Byte Order                 : Big-endian (Motorola, MM)
Make                            : Apple
Camera Model Name               : iPad mini 2
Orientation                     : Horizontal (normal)
X Resolution                    : 72
Y Resolution                    : 72
Resolution Unit                 : inches
Software                        : 8.3
Modify Date                     : 2015:09:28 16:08:35
Exposure Time                   : 1/643
F Number                        : 2.4
Exposure Program                : Program AE
ISO                             : 32
Exif Version                    : 0221
Date/Time Original              : 2015:09:28 16:08:35
Create Date                     : 2015:09:28 16:08:35
Components Configuration        : Y, Cb, Cr, -
Shutter Speed Value             : 1/643
Aperture Value                  : 2.4
Brightness Value                : 8.70472895
Exposure Compensation           : 0
Metering Mode                   : Multi-segment
Flash                           : No flash function
Focal Length                    : 3.3 mm
Subject Area                    : 1295 967 1425 851
Run Time Flags                  : Valid
Run Time Value                  : 1532568927752708
Run Time Epoch                  : 0
Run Time Scale                  : 1000000000
Sub Sec Time Original           : 957
Sub Sec Time Digitized          : 957
Flashpix Version                : 0100
Color Space                     : sRGB
Exif Image Width                : 2592
Exif Image Height               : 1936
Sensing Method                  : One-chip color area
Scene Type                      : Directly photographed
Exposure Mode                   : Auto
White Balance                   : Auto
Focal Length In 35mm Format     : 32 mm
Scene Capture Type              : Standard
Lens Info                       : 3.3mm f/2.4
Lens Make                       : Apple
Lens Model                      : iPad mini 2 back camera 3.3mm f/2.4
XMP Toolkit                     : XMP Core 5.4.0
Creator Tool                    : 8.3
Date Created                    : 2015:09:28 16:08:35
Current IPTC Digest             : d41d8cd98f00b204e9800998ecf8427e
IPTC Digest                     : d41d8cd98f00b204e9800998ecf8427e
Image Width                     : 2592
Image Height                    : 1936
Encoding Process                : Baseline DCT, Huffman coding
Bits Per Sample                 : 8
Color Components                : 3
Y Cb Cr Sub Sampling            : YCbCr4:2:0 (2 2)
Aperture                        : 2.4
Image Size                      : 2592x1936
Megapixels                      : 5.0
Run Time Since Power Up         : 17 days 17:42:48
Scale Factor To 35 mm Equivalent: 9.7
Shutter Speed                   : 1/643
Create Date                     : 2015:09:28 16:08:35.957
Date/Time Original              : 2015:09:28 16:08:35.957
Circle Of Confusion             : 0.003 mm
Field Of View                   : 58.7 deg
Focal Length                    : 3.3 mm (35 mm equivalent: 32.0 mm)
Hyperfocal Distance             : 1.46 m
Light Value                     : 13.5
